Add Document LIst and improve `build` folder (#261)
* Rename generateList to generateAppList
* Add DocumenList with Generator
* Rename Template files
* Use template file for AppList.md
* Ignore case when sorting AppList
* Organize build folder
* Add dependencies check to pre-commit script
* Add wget install collumn to tools/README.md and sort by title
* Remove Document table from README and add a link to DocumentList.md
* Remove tools table from README and add a link to the list
* Hightlight AppList on Readme

diff --git a/build/pre-commit b/build/pre-commit
--- a/build/pre-commit
+++ b/build/pre-commit
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+function error {
+  echo -e "\\e[91m$1\\e[39m"
+  exit 1
+}
+
+# Check dependencies
+jq --version &> /dev/null || error "jq is required, please install it with 'sudo apt install jq'"
+git --version &> /dev/null || error "git is required, please install it with 'sudo apt install git'"
+sha256sum --version &> /dev/null || error "sha256sum is required, please install it with 'sudo apt install coreutils'"
+
 # Check if script from build or script from hook and cd into build folder
 scriptDir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null || pwd )"
 if [ "$( echo "$scriptDir" | rev | cut -d/ -f1 | rev )" == "build" ]; then
@@ -14,11 +24,15 @@ homedir='../'
 
 # Check if Template or appinfo has changed
 if ! sha256sum -c --quiet "$verificationFile" &> /dev/null ; then
+	# Make sure tmp folder exists
+	mkdir -p "$( dirname -- "$verificationFile" )"
+
 	echo "Updating documentation..."
 	# Run all scripts
-	./generateList.sh
-	./generateREADME.sh
-	./generateToolsREADME.sh
+	./generators/generateAppList.sh
+	./generators/generateDocList.sh
+	./generators/generateREADME.sh
+	./generators/generateToolsREADME.sh
 	echo "Update finished"
 
 	# Update lastrun.sha256
@@ -28,4 +42,5 @@ if ! sha256sum -c --quiet "$verificationFile" &> /dev/null ; then
 	git add -- "$README"
 	git add -- "$TOOLSREADME"
 	git add -- "$AppList"
+	git add -- "$DocList"
 fi
